name: dot_of
description: A bundle of extensions to get something from BuildContext instead of `.of` method.
version: 0.1.0
author: Ryunosukeheaven Watanabe <heavenosk@gmail.com>
homepage: https://github.com/HeavenOSK/dot_of

environment:
  sdk: ">=2.6.0 <3.0.0"
dependencies:
  flutter:
    sdk: flutter
dev_dependencies:
  flutter_test:
    sdk: flutter
flutter:
